apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-role
rules:
  - apiGroups: ["extensions"]
    resources: ["pods", "deployments", "replicasets", "services"]
    verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-role-binding
subjects:
  - kind: ServiceAccount
    name: ci-user
roleRef:
  kind: Role
  name: ci-role
  apiGroup: rbac.authorization.k8s.io
