apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warehouse-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: execution-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: personnel-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
